"""Turns one Task into one PR.

Split of responsibility (deliberate): the *agent* only reads/writes/tests code
inside the sandboxed working tree. All git/GitHub lifecycle — branch, commit,
push, PR — is deterministic Python in this file, never a model-issued shell
command. Agents are good at fuzzy judgment (what code to write); plain code is
better at repeatable steps (the git dance) and is what you want to audit when
something goes wrong.
"""

from __future__ import annotations

import subprocess
from dataclasses import dataclass
from pathlib import Path

from claude_agent_sdk import (
    AssistantMessage,
    ClaudeAgentOptions,
    HookMatcher,
    TextBlock,
    query,
)

from agent.guardrails import bash_guardrail_hook
from tasks.base import Task

SYSTEM_PROMPT = """You are a software engineer resolving one GitHub issue in a \
local git repository. Implement the smallest correct change that resolves the \
issue. Only touch files relevant to the issue. If the repo has a test suite, \
run it with Bash and make sure it passes before you finish. Do not run `git` \
or `gh` commands yourself — committing, pushing, and opening the PR are \
handled outside your turn. When you are done, stop; do not ask questions."""


@dataclass
class RunResult:
    task: Task
    branch: str
    changed: bool
    pr_url: str | None
    log: list[str]


def _run_git(repo_path: Path, *args: str) -> subprocess.CompletedProcess:
    return subprocess.run(
        ["git", "-C", str(repo_path), *args],
        capture_output=True, text=True, check=True,
    )


async def _run_agent_turn(repo_path: Path, task: Task) -> list[str]:
    """Runs one sandboxed agent turn against the checked-out branch. Returns the
    agent's text output lines for logging."""
    options = ClaudeAgentOptions(
        system_prompt=SYSTEM_PROMPT,
        cwd=str(repo_path),
        allowed_tools=["Read", "Write", "Edit", "Glob", "Grep", "Bash"],
        hooks={"PreToolUse": [HookMatcher(matcher="Bash", hooks=[bash_guardrail_hook])]},
        max_turns=30,
    )
    prompt = f"Issue #{task.id}: {task.title}\n\n{task.body}".strip()

    lines: list[str] = []
    async for message in query(prompt=prompt, options=options):
        if isinstance(message, AssistantMessage):
            for block in message.content:
                if isinstance(block, TextBlock):
                    lines.append(block.text)
    return lines


def _default_branch(repo_path: Path) -> str:
    result = subprocess.run(
        ["gh", "repo", "view", "--json", "defaultBranchRef", "-q", ".defaultBranchRef.name"],
        capture_output=True, text=True, check=True, cwd=str(repo_path),
    )
    return result.stdout.strip()


async def run_task(repo_path: Path, task: Task, dry_run: bool = True) -> RunResult:
    branch = f"agent/issue-{task.id}"
    base = _default_branch(repo_path)
    log: list[str] = [f"Checking out {branch} from {base}"]

    # Every task branches from a freshly-updated base branch, never from
    # wherever HEAD happens to be left after a previous task — otherwise
    # sequential runs would stack each issue's diff on top of the last one's.
    _run_git(repo_path, "checkout", base)
    _run_git(repo_path, "pull", "--ff-only")
    _run_git(repo_path, "checkout", "-B", branch, base)

    log.append("Running agent turn")
    log.extend(await _run_agent_turn(repo_path, task))

    diff = _run_git(repo_path, "status", "--porcelain")
    changed = bool(diff.stdout.strip())

    if not changed:
        log.append("No changes produced — skipping commit/PR")
        return RunResult(task=task, branch=branch, changed=False, pr_url=None, log=log)

    if dry_run:
        diffstat = _run_git(repo_path, "diff", "--stat")
        log.append("Dry run — changes made but not committed:")
        log.append(diffstat.stdout)
        return RunResult(task=task, branch=branch, changed=True, pr_url=None, log=log)

    _run_git(repo_path, "add", "-A")
    _run_git(repo_path, "commit", "-m", f"Closes #{task.id}: {task.title}")
    # Push HEAD explicitly (not the local branch name): Claude Code's own
    # session checkpointing has been observed to switch HEAD to an auxiliary
    # branch mid-turn, which would silently strand our commit if we pushed
    # `branch` by name instead of by ref.
    _run_git(repo_path, "push", "-u", "origin", f"HEAD:{branch}", "--force-with-lease")

    pr = subprocess.run(
        [
            "gh", "pr", "create",
            "--repo", _remote_repo(repo_path),
            "--head", branch,
            "--title", f"{task.title} (closes #{task.id})",
            "--body", f"Automated PR generated by TicketToPR for #{task.id}.\n\nCloses #{task.id}",
        ],
        capture_output=True, text=True, check=True, cwd=str(repo_path),
    )
    pr_url = pr.stdout.strip()
    log.append(f"Opened PR: {pr_url}")
    return RunResult(task=task, branch=branch, changed=True, pr_url=pr_url, log=log)


def _remote_repo(repo_path: Path) -> str:
    result = subprocess.run(
        ["gh", "repo", "view", "--json", "nameWithOwner", "-q", ".nameWithOwner"],
        capture_output=True, text=True, check=True, cwd=str(repo_path),
    )
    return result.stdout.strip()
